### ISSUE TITLE
Create the main menu

### ISSUE THREAD

**Issue by luiscaceresd** [luiscaceresd/deadline#1]
The user should be able to enter and exit the game using the main menu.

**Comment by saumorsomething** [comment]
Estimated time: 2 hours

Actual time: 4 hours

First hour was spent finding the models I wanted, setting up the scenes, and navigating some unity features such as "videoplayer". 
2 hours was spent writing the code for the zoom and fade transition into the next scene, and the logic for the other buttons. Last hour was spent resolving issues involving pushing the changes using GitBash. Had to use git LFS due to the large filesize.
